const galleryWorks = [
  { title: "イラスト練習", year: 2026, image: "gallery-images/01.jpg", fullImage: "gallery-images-full/01.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/02.jpg", fullImage: "gallery-images-full/02.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/03.jpg", fullImage: "gallery-images-full/03.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/04.jpg", fullImage: "gallery-images-full/04.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/05.jpg", fullImage: "gallery-images-full/05.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/06.jpg", fullImage: "gallery-images-full/06.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/07.jpg", fullImage: "gallery-images-full/07.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/08.jpg", fullImage: "gallery-images-full/08.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/09.jpg", fullImage: "gallery-images-full/09.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/10.jpg", fullImage: "gallery-images-full/10.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/11.jpg", fullImage: "gallery-images-full/11.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/12.jpg", fullImage: "gallery-images-full/12.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/13.jpg", fullImage: "gallery-images-full/13.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/14.jpg", fullImage: "gallery-images-full/14.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/15.jpg", fullImage: "gallery-images-full/15.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/16.jpg", fullImage: "gallery-images-full/16.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/17.jpg", fullImage: "gallery-images-full/17.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/18.jpg", fullImage: "gallery-images-full/18.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/19.jpg", fullImage: "gallery-images-full/19.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/20.jpg", fullImage: "gallery-images-full/20.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/21.jpg", fullImage: "gallery-images-full/21.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/22.jpg", fullImage: "gallery-images-full/22.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/23.jpg", fullImage: "gallery-images-full/23.jpg" },
  { title: "イラスト練習", year: 2026, image: "gallery-images/24.jpg", fullImage: "gallery-images-full/24.jpg" },
  { title: "イラスト練習", year: 2025, image: "gallery-images/25.jpg", fullImage: "gallery-images-full/25.jpg" },
  { title: "イラスト練習", year: 2025, image: "gallery-images/26.jpg", fullImage: "gallery-images-full/26.jpg" }
];
